apiVersion: v1
kind: ReplicationController
metadata:
  name: coffee-rc-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-2
    spec:
      containers:
      - name: coffee-2
        image: nginxdemos/hello
        ports:
        - containerPort: 80