apiVersion: v1
kind: ReplicationController
metadata:
  name: tea-rc-2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tea-2
    spec:
      containers:
      - name: tea-2
        image: nginxdemos/hello
        ports:
        - containerPort: 80