apiVersion: v1
kind: ReplicationController
metadata:
  name: pssim-api-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pssim-api
    spec:
      containers:
      - name: pssim-api
        image: ivancaro/test:latest
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux