apiVersion: apps/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: catastro-api
  labels:
    app: catastro-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catastro-api
  template:
    metadata:
      labels:
        app: catastro-api
    spec:
      containers:
      - name: catastro-api
        image: minvu.azurecr.io/catastro_api:44e8272b363821e7a4e45ee90a7c0353469cbd0e
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "0c81b8d7-7910-4755-b0eb-dc83cd3e75ad"
        - name: PSSIM_URI
          value: "pssim-api.minvu.cl"
        - name: REDIS_URL
          value: "clminvu-catastro.redis.cache.windows.net"
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_PASS
          value: "dgLmwMCN6MVjQg/cok1r4b1o3X+B1KFF8nr5z37WNOA="
        - name: ConnectionDb
          value: "mongodb://clminvu-catastro:HnmNvLcAGTvPoXtwM1wc2VdHuDfhdKBQ8EqlAIsdLp3sfKGiKmOx4Hlllelrf4ycGc2XL3IPTUTMPN0am94ZPQ==@clminvu-catastro.documents.azure.com:10255/?ssl=true"
        - name: AZURE_STORAGE_ACCOUNT
          value: "clminvustgcatastro"
        - name: AZURE_STORAGE_ACCESS_KEY
          value: "R7QpgAnqZIsJLY6DRJFeAJoMXZ61ByWxlVaCbOUipRwBvgtdeElOwSG+7+iXkOduBQLIfIUfqwkZ0TWWi21Mag=="
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=clminvustgcatastro;AccountKey=R7QpgAnqZIsJLY6DRJFeAJoMXZ61ByWxlVaCbOUipRwBvgtdeElOwSG+7+iXkOduBQLIfIUfqwkZ0TWWi21Mag==;EndpointSuffix=core.windows.net"
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: azureregistry
