apiVersion: v1
kind: ReplicationController
metadata:
  name: pssim-api2-nginx-ingress-rc
  labels:
    app: pssim-api2-nginx-ingress
spec:
  replicas: 1
  selector:
    app: pssim-api2-nginx-ingress
  template:
    metadata:
      labels:
        app: pssim-api2-nginx-ingress
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:1.0.0
        imagePullPolicy: Always
        name: pssim-api2-nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
        args:
         #- -v=3
         #- -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret-pssim